portainer/portainer-docs

docs/source/contribute.rst
docs/source/index.rst

docs(contribute): add a Contribute section

---

docs/source/deployment.rst

Fix simple mistake where the "volume" parameter is in the wrong place

fix(deployment): fix run with TLS

---

docs/source/templates.rst

docs(templates): document the type field for the environment variables

---

docs/source/templates.rst

Related to https://github.com/portainer/templates/issues/42

docs(templates): add a section about the command field

---

docs/source/templates.rst

Related to https://github.com/portainer/templates/issues/44

docs(templates): add a section about the network field

---

docs/source/configuration.rst

Would fix portainer/portainer#554 👍

Small note about size of a custom logo

---

docs/source/templates.rst

Related to https://github.com/portainer/portainer/issues/643

docs(templates): add a section about the privileged field

---

docs/source/configuration.rst
docs/source/deployment.rst

docs(ssl): document the ability to start Portainer using SSL

---

docs/source/index.rst
docs/source/limitations.rst

docs(limitations): add a limitations section

---

docs/source/agent.rst
docs/source/deployment.rst

Fixes #50 
Explains Agent deployment for Windows.

Updated Windows deployment guides

---

docs/source/deployment.rst

Found small typo from Windows containers start command

fix(win): corrected Win container mount command

---

docs/source/configuration.rst

docs(configuration): make admin-password clearer

---

docs/source/faq.rst

at least, i think this is the case :)

portainer agent is open source now?

---

docs/source/configuration.rst

Adds the --tunnel-port flag to the config page

docs(configuration): add the --tunnel-port flag

---

docs/source/templates.rst

docs(templates): add type limitation note

---

docs/v2.0/troubleshooting/troubleshooting.md

Just shift to Shift for consistent flow.

Case issue only

---

docs/v2.0-be/deploy/cli.md

NB: Some changes from auto-formatting

Update cli documentation with rollback option

---

docs/v2.0/deploy/initial.md

Transfer the documentation about the different password setup options from the old documentation of 1.x

Add information about password setup options

---

docs/v2.0/deploy/linux.md

The grammar ninja wuz here! ⚔️

Minor grammatical fix

---

docs/v2.0/images/pull.md

typo in the url for adding registries

fixing typo

---

docs/css/extra.css
docs/index.md
docs/quickstart.md
docs/v2.0-be/deploy/beinstalldocker.md
docs/v2.0-be/deploy/beinstallk8s.md
docs/v2.0-be/deploy/beinstallswarm.md
docs/v2.0/deploy/ceinstalldocker.md
docs/v2.0/deploy/ceinstallk8s.md
docs/v2.0/deploy/ceinstallswarm.md
docs/v2.0/deploy/roles.md
docs/v2.0/deploy/singleinstalldocker.md
docs/v2.0/upgrade/upddocker.md
docs/v2.0/upgrade/updk8s.md
docs/v2.0/upgrade/updswarm.md
docs/v2.0/upgrade/upgrade.md
mkdocs.yml

Re-Organised Docs and changed a few aesthetics

QuickStart and Re-Organise

---

docs/v2.0-be/deploy/beinstalldocker.md
docs/v2.0-be/deploy/beinstallk8s.md
docs/v2.0-be/deploy/beinstallswarm.md
docs/v2.0-be/upgrade/upddocker.md
docs/v2.0-be/upgrade/updk8s.md
docs/v2.0-be/upgrade/updswarm.md
docs/v2.0/deploy/ceinstalldocker.md
docs/v2.0/deploy/ceinstallk8s.md
docs/v2.0/deploy/ceinstallswarm.md
docs/v2.0/upgrade/upddocker.md
docs/v2.0/upgrade/updk8s.md
docs/v2.0/upgrade/updswarm.md

agent only network driver overlay

agent version match warning

---

docs/v2.0/deploy/ceinstalldocker.md
docs/v2.0/deploy/ceinstallk8s.md
docs/v2.0/deploy/ceinstallswarm.md

Add pre-requisites to CE Install instructions

Pre-Reqs to CE Install Docs

---

docs/index.md

Hey Guys ,
I fixed (I think) the consistency of the spelling of "open source"
Some sentences were a bit wordy.
Some sentences lacked punctuation that may have contributed to an unclear image in the reader's mind or made for an awkward read..
Hope this helps

Grammar Mostly

---

contributing.md

Updated Link Previews

---

docs/v2.0-be/deploy/ssl.md
docs/v2.0/deploy/ssl.md

Added SSL generation / certbot steps
